### PR TITLE
Remove Go module files

### PR DESCRIPTION
**Pull request by remingtonc**
Removing `go.mod` and `go.sum` per [comments](https://github.com/cisco-ie/pipeline-gnmi/commit/70a0c53604145212a7d02aac588dd41aea9826a0#commitcomment-33695879). Also related to #5 and the ongoing `jsonpb` issues.

@nleiva as someone who is contributing a bit, simply made you a contributor to keep it easy.

### CODE REVIEW

**Comment by nleiva** [comment]
Instead of removing them, we might want to replace them for the correct ones (so we support Go 1.12+). In order to generate them, execute this `go mod init github.com/cisco-ie/pipeline-gnmi` at the root of the repo. It will add a new `go.mod` and `go.sum`.

**Comment by remingtonc** [comment]
My current problem is that when building with Go modules there are multiple failures with jsonpb. Not using Go modules still works exclusively because the [`vendor/`ed code itself contains the patch](https://github.com/cisco-ie/pipeline-gnmi/blob/master/vendor/github.com/golang/protobuf/jsonpb/jsonpb.go#L628). We are inherently broken here the moment we stop using vendor. Can test from `go-modules` branch and set `GO111MODULE=on` in `docker/Dockerfile`.

**Comment by nleiva** [comment]
Thanks for the branch, I’ll work on it next week. I’ll keep you posted.

**Review by BenderScript — APPROVED** [review]
LGTM

**Comment by BenderScript** [comment]
We should definitely have a separate branch for that. The transition to Go mod should be very smooth and thoroughly tested (lots of Stackoverflow horror stories).  We should test building outside the GOPATH in a fresh install. As soon as @remingtonc get Travis running on the repo we can hopefully created a new Go Mod job.

**Pull request merged**
